import os
import re

summaries = {
    "glean-ml-engineer-llm-evals": "Applied AI engineer (2.5+ years) with LLM evaluation and observability infrastructure as primary production specialty. Healthcare RAG evaluation pipelines with retrieval-grounded alignment &gt;90% in eval, ~35% retrieval precision gain. Hallucination measurement framework on Suvidha document Q&amp;A: hallucinations -30%, contextual accuracy &gt;85%. Agentic LLM workflows with schema-validated JSON contracts to prevent cascading hallucinations (Agentic Healthcare Claims). FastAPI/Flask production services on Docker with structured logging and load simulation; post-deploy defects -30%. Grafana plus DMV dashboards for performance observability. Ready to design eval datasets, build LLM judges, and ship observability infrastructure for Glean enterprise AI assistant.",
    "deepgram-fde-restaurants-nyc": "Applied AI engineer (2.5+ years) with end-to-end deployment and multi-provider integration as primary production specialty. Healthcare RAG production with HIPAA-conscious governance: ~35% retrieval precision gain, &gt;90% retrieval-grounded alignment, ~30% post-deployment defect reduction. Solo shipped Manga Lens to Chrome Web Store with four AI vision providers (Claude, GPT-4o, 4.1 Nano, Ollama local) and per-domain selector configs for 29 sites. Agentic LLM workflows and schema-validated JSON contracts (Agentic Healthcare Claims). Transformer-based video summarization at Suvidha. Ready to embed with Deepgram restaurant customers and integrate voice agents into the core of their operations.",
    "deepgram-backend-swe-voice-agent": "Applied AI engineer (2.5+ years) building backend services for AI model chains. FastAPI/Flask production services on Docker with structured logging and load simulation; ~30% post-deploy defect reduction. Multi-provider AI vision integration in Manga Lens (Claude, GPT-4o, 4.1 Nano, Ollama local) shipped to Chrome Web Store. Healthcare RAG with HIPAA-conscious governance: &gt;90% retrieval-grounded alignment, ~35% retrieval precision gain. Agentic Healthcare Claims with schema-validated JSON contracts preventing cascading hallucinations. Transformer-based audio transcript preprocessing at Suvidha. Ready to design and implement secure, scalable services for Deepgram Voice Agent speech processing and telephony + RAG integrations.",
    "deepgram-swe-voice-agents-restaurants-sf": "Applied AI engineer (2.5+ years) building agentic LLM workflows with grounding rules and structured outputs. Healthcare agentic LLM with multi-step queries: response stability +25%, hallucinations -30%. Agentic Healthcare Claims multi-agent pipeline (Intake to Validation to Consistency to Duplicate to Fraud) with schema-validated JSON contracts. Healthcare RAG: ~35% retrieval precision, &gt;90% grounded-alignment. Transformer-based audio transcript preprocessing at Suvidha. Driver drowsiness real-time YOLOv8 detection. Ready to build voice agents for Deepgram restaurants vertical with menu-aware NLP and real-time operational intelligence.",
    "claylabs-swe-developer-experience-ai": "Applied AI engineer (2.5+ years) building infrastructure for agentic LLM workflows with schema-validated JSON contracts. Agentic Healthcare Claims multi-agent pipeline (Intake to Validation to Consistency to Duplicate to Fraud Risk) with schema-validated contracts preventing cascading hallucinations. Multi-provider AI vision orchestration in Manga Lens (Claude, GPT-4o, 4.1 Nano, Ollama local) shipped to Chrome Web Store. Healthcare RAG production with HIPAA-conscious governance: ~35% retrieval precision gain, &gt;90% grounded-alignment. FastAPI/Flask production services on Docker with structured logging; post-deploy defects -30%. CI/CD Jenkins with version-controlled SQL and rollback checkpoints. Ready to build the engineering infrastructure that lets coding agents operate safely in Clay production codebase.",
    "baseten-applied-ai-inference-engineer": "Applied AI engineer (2.5+ years) with end-to-end production AI deployment as primary specialty. Healthcare RAG production with HIPAA-conscious governance: ~35% retrieval precision gain, &gt;90% retrieval-grounded alignment, ~30% post-deployment defect reduction. Agentic LLM workflows and schema-validated JSON contracts (Agentic Healthcare Claims). Multi-provider AI orchestration in Manga Lens shipped to Chrome Web Store. FastAPI/Flask production services on Docker with structured logging and load simulation. Stakeholder-facing system-limitation docs and evaluation audit trails. E-Farming founder shipping full-stack PHP/MySQL marketplace to 80-120 users. Ready to partner with Baseten customers from problem framing through production deployment and monitoring.",
    "baseten-swe-ai-enablement": "Applied AI engineer (2.5+ years) building internal AI tooling and agent infrastructure. Multi-provider AI vision orchestration in Manga Lens (Claude, GPT-4o, 4.1 Nano, Ollama local) shipped to Chrome Web Store with per-provider payload handling. Agentic Healthcare Claims multi-agent pipeline with schema-validated JSON contracts (Intake to Validation to Consistency to Duplicate to Fraud). Healthcare agentic LLM workflows: response stability +25%, hallucinations -30%. FastAPI/Flask production services on Docker. Evaluation audit trails and Grafana plus DMV dashboards for observability. Ready to own Baseten internal AI agents, coding assistants, and LLM-powered SDLC tooling.",
    "crosby-ai-developer-experience-engineer": "Applied AI engineer (2.5+ years) building eval, prompt management, and experimentation infrastructure for production LLM systems. Healthcare RAG eval pipelines with retrieval-grounded alignment &gt;90%, ~35% retrieval precision gain; full HIPAA-conscious evaluation audit trails. Hallucination measurement framework on Suvidha document Q&amp;A: hallucinations -30%, contextual accuracy &gt;85%. Multi-provider AI orchestration in Manga Lens with payload-handling tradeoffs across four providers. Agentic Healthcare Claims with schema-validated JSON contracts preventing cascading hallucinations. Stable Diffusion plus LoRA fine-tuning experience. Ready to build the internal AI dev tooling that lets Crosby ship legal AI features faster and more reliably.",
    "baseten-swe-voice-ai-inference-runtime": "Applied AI engineer (2.5+ years) building real-time inference services for production AI systems. Driver drowsiness real-time YOLOv8 fatigue monitoring with ~30% inference latency reduction via unified detection-and-classification model and adaptive frame skipping. Multi-provider AI vision serving in Manga Lens (Claude, GPT-4o, 4.1 Nano, Ollama local) with payload-handling per provider. FastAPI/Flask production services on Docker with structured logging; ~30% post-deploy defect reduction. Healthcare RAG production with HIPAA-conscious governance. Agentic LLM workflows and schema-validated JSON contracts. Transformer-based audio transcript preprocessing at Suvidha. Ready to ramp into Baseten Voice AI inference stack for STT/TTS serving, latency tuning, and real-time agent orchestration.",
    "baseten-swe-training-product": "Applied AI engineer (2.5+ years) with full-stack shipping muscle and end-to-end model lifecycle experience. E-Farming founder shipping full-stack PHP/MySQL marketplace to 80-120 users. Manga Lens shipped to Chrome Web Store full-stack (Manifest V3, service workers, captureVisibleTab). Dream Decoder full-stack FastAPI plus React/TypeScript/Vite app with multimodal API orchestration. Stable Diffusion plus LoRA fine-tuning for identity-consistent character generation, ControlNet plus OpenPose conditioning. FastAPI/Flask production services on Docker. Healthcare RAG production with HIPAA-conscious governance. Ready to own Baseten Training Product features end-to-end from API/UI to infrastructure layer and partner with research engineers on SOTA training techniques.",
    "mistral-ai-engineer-product-paris": "Applied AI engineer (2.5+ years) embedded in product teams to improve AI quality end-to-end. Healthcare RAG eval pipelines: retrieval-grounded alignment &gt;90%, ~35% retrieval precision gain, full evaluation audit trails. Hallucination measurement framework on Suvidha document Q&amp;A: hallucinations -30%, contextual accuracy &gt;85%. Agentic LLM workflows with tool discipline and grounding rules: response stability +25%. Multi-provider AI orchestration in Manga Lens (Claude, GPT-4o, 4.1 Nano, Ollama local) with per-provider experimentation. Dream Decoder intermediate structured prompt-transformation layers: +30% contextual alignment, +25-30% first-pass success. Python primary, TypeScript via Manga Lens and Dream Decoder. Ready to own AI quality for Mistral product features: design evals, run experiments, measure metrics, ship improvements.",
    "super-ai-ml-engineer-berlin-remote-eu": "Applied AI engineer (2.5+ years) deploying and managing production AI workloads for enterprise customers. Healthcare RAG production with HIPAA-conscious governance: ~35% retrieval precision gain, &gt;90% retrieval-grounded alignment, ~30% post-deployment defect reduction. FastAPI/Flask production services on Docker with structured logging and load simulation. Agentic LLM workflows and schema-validated JSON contracts (Agentic Healthcare Claims). Multi-provider LLM orchestration in Manga Lens (Claude, GPT-4o, 4.1 Nano, Ollama local). Cloud-ready deployment patterns; Stable Diffusion LoRA fine-tuning experience. Stakeholder-facing system-limitation docs and evaluation audit trails. Ready to deploy and manage super.AI enterprise AI workloads with Python, Docker, cloud, LLMs, prompt engineering."
}

TMP_DIR = "C:/Users/deepa/AppData/Local/Temp"

failed = []
for slug, new_summary in summaries.items():
    path = f"{TMP_DIR}/cv-{slug}.html"
    try:
        with open(path, "r", encoding="utf-8") as f:
            html = f.read()
        m = re.search(r'<div class="summary-text">.*?</div>', html, re.DOTALL)
        if m:
            html = html.replace(m.group(0), f'<div class="summary-text">{new_summary}</div>')
            with open(path, "w", encoding="utf-8") as f:
                f.write(html)
            print(f"OK: {slug}")
        else:
            failed.append(slug)
            print(f"FAIL no summary div: {slug}")
    except Exception as e:
        failed.append(f"{slug}: {e}")
        print(f"FAIL: {slug}: {e}")

if failed:
    print(f"FAILED: {failed}")
else:
    print("All summaries tailored.")
